### ISSUE TITLE
syntax error when running installer

### ISSUE THREAD

**Issue by klotfi** [IBM-Cloud/ibm-cloud-developer-tools#62] opened 2018-07-30 16:04 UTC
**Summary**

**Steps to reproduce**
(include tooling version, platform, etc)
1.  follow the instruction listed here: https://console.bluemix.net/docs/cli/index.html#overview
2. run curl -sL http://ibm.biz/idt-installer | bash
and I am getting the following error:
bash: line 1: syntax error near unexpected token `newline'
bash: line 1: `<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">'

**Operating System**
Specify:  Linux version 3.10.0-862.3.3.el7.x86_64

**Supporting details**
(Logs, stack traces, images, etc.  Wrap in `<detail> ... </detail>` tags as appropriate)

-----------------------------------

**Development "done" checklist**

- [ ] Test case to verify
- [ ] Public Documentation updated
- [ ] Change added to "release notes" as appropropriate
- [ ] Notification to stakeholders (OM, other squads, etc)

**Comment by steveclay** [comment] 2018-08-10 18:38
@klotfi what Linux distro are you using, etc.?  I just retested with `Ubuntu 16.04.3 LTS ` and did not see the failure you are seeing.

You also might take these approaches:

1.  Download the installer from https://github.com/IBM-Cloud/ibm-cloud-developer-tools, and run the script in the `linux-installer` folder.

2.  If all else fails, on this page we offer the manual instructions for all the tools the `idt-installer` installs:  https://console.bluemix.net/docs/cli/ts_createapps.html#appendix

**Comment by triceam** [comment] 2018-08-30 18:45
Closing - Unable to reproduce
Only things I can think that would cause this would be a typo/copy paste error, or an unsupported linux distro.

**Closed by triceam** 2018-08-30 18:45 UTC
